import Model1 from "../../assets/models/1.jpg";
import Model2 from "../../assets/models/2.jpg";
import Model3 from "../../assets/models/3.jpg";
import Model4 from "../../assets/models/4.jpg";
import Model5 from "../../assets/models/5.jpg";
import Model6 from "../../assets/models/6.jpg";

export const IN_STOCK_DATA = [
  {
    name: "Exclusive 51P",
    image: Model1,
    link: "exclusive-51p",
    price: 13500,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "I-Glass Vertical",
    image: Model2,
    link: "i-glass-vertical",
    price: 11000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Brilliant",
    image: Model3,
    link: "brilliant",
    price: 10000,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Exclusive 74P",
    image: Model4,
    link: "exclusive-74p",
    price: 14000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Exclusive 74S",
    image: Model5,
    link: "exclusive-74s",
    price: 17500,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Islandzero",
    image: Model6,
    link: "islandzero",
    price: 20000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Exclusive 45P",
    image: Model1,
    link: "exclusive-45p",
    price: 13500,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "I-Glass Vertical2",
    image: Model2,
    link: "i-glass-vertical2",
    price: 11000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Brilliant3",
    image: Model3,
    link: "brilliant3",
    price: 10000,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Exclusive 79P",
    image: Model4,
    link: "exclusive-79p",
    price: 14000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Exclusive 34S",
    image: Model5,
    link: "exclusive-34s",
    price: 17500,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Islandzero4",
    image: Model6,
    link: "islandzero4",
    price: 20000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Exclusive 49P",
    image: Model1,
    link: "exclusive-49p",
    price: 13500,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "I-Glass Vertical4",
    image: Model2,
    link: "i-glass-vertical4",
    price: 11000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Brilliant1",
    image: Model3,
    link: "brilliant1",
    price: 10000,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Exclusive 58P",
    image: Model4,
    link: "exclusive-58p",
    price: 14000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Exclusive 33S",
    image: Model5,
    link: "exclusive-33s",
    price: 17500,
    type: "pastry",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
  {
    name: "Islandzero6",
    image: Model6,
    link: "islandzero6",
    price: 20000,
    type: "gastronomic",
    width: 250,
    deep: 150,
    mirror_height: 100,
    shelves: 3,
  },
];
